spring.application.name=TaskManager

spring.datasource.url=jdbc:postgresql://ep-square-water-b3p4vfj1-pooler.c-4.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_0Xhegp6RWEij
spring.jpa.hibernate.ddl-auto=update